# Page d'accueil (fichier racine)
["projet2.py"]
title = "Accueil"
icon = "ğŸ "

# Pages dans le dossier 'pages/'
[pages."page1.py"]
title = "Recommandations"
icon = "ğŸ¯"

[pages."page2.py"]
title = "Film par film"
icon = "ğŸ¬"

[pages."page3.py"]
title = "La Creuse au cinÃ©ma"
icon = "ğŸŒ„"

[pages."page4.py"]
title = "Notre fonds cinÃ©matographique"
icon = "ğŸ“š"